import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "./components/sidebar/Sidebar";
import Navbar from "./navbar/Navbar";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html data-theme="halloween" lang="en">
      <body className={inter.className}>
        <Navbar />
        <Sidebar children={children} />
      
      </body>
    </html>
  );
}
